//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZH.Dbf
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestServe
    {
        public int id { get; set; }
        public int employeId { get; set; }
        public int requestId { get; set; }
        public string status { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Request Request { get; set; }
    }
}
